#기본코드

In [0]:
!pip install -U finance-datareader
import FinanceDataReader as fdr
df_krx = fdr.StockListing('KRX')

In [0]:
import mpl_finance 
from mpl_finance import candlestick2_ohlc
%matplotlib inline
import matplotlib.ticker as ticker
import numpy as np
import pandas_datareader.data as web
import datetime
from sklearn import linear_model
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
matplotlib.style.use('ggplot')
import pandas as pd 
import FinanceDataReader as fdr

In [0]:

name=input('주식 코드 기업명 ?')
#find 종목 코드 및 정보
df_krx[df_krx['Name'].str.contains(name)]

주식 코드 기업명 ?전자랜드

Empty DataFrame
Columns: [Symbol, Name, Sector, Industry]
Index: []

In [5]:
kospi = fdr.DataReader('KS11', '2015-01-01','2019-11-25')
삼성=fdr.DataReader('005930', '2015-01-01','2019-11-25')
한전=fdr.DataReader('015760', '2015-01-01','2019-11-25')
SKT=fdr.DataReader('017670', '2015-01-01','2019-11-25')
포스코=fdr.DataReader('005490', '2015-01-01','2019-11-25')
현대차=fdr.DataReader('005380', '2015-01-01','2019-11-25')

현대차

              Open    High     Low   Close  Volume    Change
Date
2015-01-02  169000  170500  167000  169000  458014  0.000000
2015-01-05  171000  171000  166000  168000  454073 -0.005917
2015-01-06  166500  167000  164000  164500  635059 -0.020833
2015-01-07  163000  171500  163000  170000  511006  0.033435
2015-01-08  172500  178000  171000  178000  902742  0.047059
...            ...     ...     ...     ...     ...       ...
2019-11-19  125000  126000  124500  125000  537780 -0.007937
2019-11-20  124500  124500  123500  124500  593391 -0.004000
2019-11-21  124000  124500  123000  124500  724349  0.000000
2019-11-22  124000  125500  123500  123500  707333 -0.008032
2019-11-25  124000  125500  123500  125000  640837  0.012146

[1203 rows x 6 columns]

In [6]:
df =  pd.concat([kospi['Close'],삼성['Close'],한전['Close'],SKT['Close'],
                 포스코['Close'],현대차['Close']],axis=1)
df.set_axis(['ko','ss','gg','skt','po','hd'],axis=1,inplace=True)
#df.columns = (['코스피','삼성','한전','SKT','포스코','현대차'],axis=1)
df.head(3)

                 ko     ss     gg     skt      po      hd
Date
2015-01-02  1926.44  26600  42700  272500  283500  169000
2015-01-05  1915.75  26660  42000  276500  279000  168000
2015-01-06  1882.45  25900  41850  274500  275000  164500

In [7]:
df_rev = df.diff(axis = 0 , periods = 1) / df.shift(periods = 1)
df_rev.dropna(inplace = True)
df_rev.head(3)
#diff (오늘종가 - 어제종가 )/ shift (어제종가) 
##내가 기간을 5일전을 한다 --- periods = 5 로 하면뎀 (shift도 5로 )

                  ko        ss        gg       skt        po        hd
Date
2015-01-05 -0.005549  0.002256 -0.016393  0.014679 -0.015873 -0.005917
2015-01-06 -0.017382 -0.028507 -0.003571 -0.007233 -0.014337 -0.020833
2015-01-07  0.000733  0.009266  0.031063 -0.018215  0.016364  0.033435

#1204 팝퀴즈 괜찮은기업(짝수)의 일별 투자 수익률을 구하시오, 학번 20182890

In [34]:
kos = fdr.DataReader('KS11', '2019-01-01','2019-12-04')
모나미=fdr.DataReader('005360', '2019-01-01','2019-12-04')
효성=fdr.DataReader('004800', '2019-01-01','2019-12-04')
에이치시티=fdr.DataReader('072990', '2019-01-01','2019-12-04')
삼성전자=fdr.DataReader('005930', '2019-01-01','2019-12-04')
SK하이닉스=fdr.DataReader('000660', '2019-01-01','2019-12-04')

SK하이닉스

             Open   High    Low  Close    Volume    Change
Date
2019-01-02  61300  61400  60000  60600   1934295  0.001653
2019-01-03  60200  60300  57500  57700   3337621 -0.047855
2019-01-04  57500  58500  56700  58300   3388087  0.010399
2019-01-07  59000  59700  58400  58700   2273750  0.006861
2019-01-08  57900  60500  57600  59200   3062192  0.008518
...           ...    ...    ...    ...       ...       ...
2019-11-28  83100  83800  82500  82800   1413983  0.001209
2019-11-29  82500  82800  80700  80900   2139440 -0.022947
2019-12-02  80900  81800  80500  80500   1945991 -0.004944
2019-12-03  78100  79300  77300  78700  11657151 -0.022360
2019-12-04  78000  78100  76800  77700   6164549 -0.012706

[229 rows x 6 columns]

In [114]:
qw =  pd.concat([모나미['Close'],효성['Close'],에이치시티['Close'],
                 삼성전자['Close'],SK하이닉스['Close']],axis=1)
qw.set_axis(['MO','HS','HCT','SS','SK'],axis=1,inplace=True)
#df.columns = (['KO','MO','HS','HCT','SS','SK'],axis=1)
qw.head(3)

              MO     HS   HCT     SS     SK
Date
2019-01-02  2640  47950  6038  38750  60600
2019-01-03  2655  48450  5811  37600  57700
2019-01-04  2640  47300  5758  37450  58300

In [107]:
rev = qw.diff(axis = 0 , periods = 1) / qw.shift(periods = 1)
rev.dropna(inplace = True)
rev.head(3)
#diff (오늘종가 - 어제종가 )/ shift (어제종가) 
##내가 기간을 5일전을 한다 --- periods = 5 로 하면뎀 (shift도 5로 )

                  KO        MO        HS       HCT        SS        SK
Date
2019-01-03 -0.008109  0.005682  0.010428 -0.037595 -0.029677 -0.047855
2019-01-04  0.008301 -0.005650 -0.023736 -0.009121 -0.003989  0.010399
2019-01-07  0.013357  0.039773  0.007400  0.017367  0.034713  0.006861

In [98]:
rev.shape[0]

228

In [116]:
import numpy as np
rev= np.array(rev)
one =np.array(np.repeat(1,rev.shape[0]))
one.shape

(228,)

In [117]:
exp = one.T@rev/rev.shape[0]
exp

array([0.00240758, 0.00239208, 0.0025609 , 0.00117443, 0.00133763])

##수익률 공분산 구하기

In [125]:
exp_repeat = np.tile(exp,(rev.shape[0],1))
exp_repeat.shape
A = rev.T - exp_repeat.T # (5, 1205)
B = rev - exp_repeat # (1205, 5)
(A @ B) #(5, 5)
cov_fn = (A @ B)/rev.shape[0]
cov_fn

array([[ 2.63432997e-03,  1.20002328e-05, -4.73766503e-05,
        -5.10992233e-05, -6.93659930e-05],
       [ 1.20002328e-05,  3.61709099e-04,  1.15376032e-04,
         1.89460989e-05,  2.16439195e-05],
       [-4.73766503e-05,  1.15376032e-04,  9.52223304e-04,
         1.25391759e-04,  1.44668298e-04],
       [-5.10992233e-05,  1.89460989e-05,  1.25391759e-04,
         2.09077639e-04,  2.21373584e-04],
       [-6.93659930e-05,  2.16439195e-05,  1.44668298e-04,
         2.21373584e-04,  4.96035716e-04]])

##투자포트폴리오  기대수익률 , 위험분산 구하기

In [0]:
import numpy as np 
pf = np.array([[0.2, 0.2, 0.2, 0.2, 0.2],
              [0.35, 0.35, 0.1, 0.1, 0.1],
              [0.05, 0.05, 0.3, 0.3, 0.3]])

In [136]:
pf@exp

array([0.00197453, 0.00218718, 0.00176187])

In [135]:
pf[1]@cov_fn@pf[1].T #p2의 분산
pf[0]@cov_fn@pf[0].T #p1의 분산
pf[2]@cov_fn@pf[2].T #p3의 분산
pf@cov_fn@pf.T

array([[0.00022546, 0.00026314, 0.00018778],
       [0.00026314, 0.00039553, 0.00013075],
       [0.00018778, 0.00013075, 0.00024481]])

기대수익률 1번 , 위험분산이 가장 낮은 것은 2번

##최소분산 포트폴리오

지이이이인짜 모르겠다.

In [168]:
#inverse?

import numpy.linalg as la  
aaa = la.inv(cov_fn)
aaa

array([[ 3.81728960e+02, -2.04501785e+01,  9.40937243e+00,
         6.62522024e+01,  2.19619368e+01],
       [-2.04501785e+01,  2.87749951e+03, -3.41615436e+02,
        -5.76210813e+01, -3.06874273e+00],
       [ 9.40937243e+00, -3.41615436e+02,  1.18161191e+03,
        -6.21258692e+02, -5.11352951e+01],
       [ 6.62522024e+01, -5.76210813e+01, -6.21258692e+02,
         9.42730092e+03, -4.01429996e+03],
       [ 2.19619368e+01, -3.06874273e+00, -5.11352951e+01,
        -4.01429996e+03,  3.82562665e+03]])

In [166]:
pf[0]@cov_fn@pf[0].T 
pf[1]@cov_fn@pf[1].T 
pf[2]@cov_fn@pf[2].T

0.0002448121788580817

In [162]:
exp@cov_fn

array([6.09694668e-06, 1.24079970e-06, 2.94125608e-06, 7.85074883e-07,
       1.17875178e-06])

In [161]:
aaa.T@exp

array([1.00140763, 5.88736417, 1.43344992, 4.13277669, 0.31732569])

#기말고사 준비자료 4개기업 나만의 포트폴리오를 만들어오세요.